
cache1:
  image: memcached
  expose:
   - 11211
  ports:
   - "11211:11211"

cache2:
  image: memcached
  expose:
   - 11211
  ports:
   - "11212:11211"

redis:
  image: redis
  container_name: redis-cluster
  expose:
    - 6379
  ports:
    - "6379:6379"
  command: redis-server

postgres:
  image: octi/postgres
  container_name: postgres
  expose:
    - 5432
  ports:
      - "5432:5432"
  environment:
    - POSTGRES_DB=octi
    - POSTGRES_USER=octi
    - POSTGRES_PASSWORD=octi

configservice:
  image: octi/configservice:latest
  restart: always
  ports:
    - 8888:8888

discovery:
  image: octi/discovery:latest
  restart: always
  ports:
    - 8761:8761
  links:
    - configservice

users:
  image: octi/users:my
  container_name: users
  restart: always
  ports:
    - 8585:8585
  links:
    - redis
    - discovery
    - configservice
    - cache1:cache1
    - cache2:cache2
    - postgres:db
  environment:
    - active.profile=default
    - configservice.url=http://configservice:8888
    - discovery.url=http://discovery:8761/eureka/

octis:
  image: octi/octis:latest
  container_name: octis
  restart: always
  ports:
    - 8085:8085
  links:
    - redis
    - discovery
    - configservice
    - cache1:cache1
    - cache2:cache2
    - postgres:db
  environment:
    - active.profile=default
    - configservice.url=http://configservice:8888
    - discovery.url=http://discovery:8761/eureka/

graph:
  image: octi/graph:my
  container_name: graph
  restart: always
  ports:
    - 9595:9595
  links:
    - redis
    - discovery
    - configservice
    - cache1:cache1
    - cache2:cache2
  environment:
    - active.profile=default
    - configservice.url=http://configservice:8888
    - discovery.url=http://discovery:8761/eureka/

feeds:
  image: octi/feeds:my
  container_name: feeds
  restart: always
  ports:
    - 9090:9090
  links:
    - redis
    - discovery
    - configservice
    - cache1
    - cache2
  environment:
    - active.profile=default
    - configservice.url=http://configservice:8888
    - discovery.url=http://discovery:8761/eureka/

apigateway:
  image: octi/apigateway:latest
  container_name: apigateway
  restart: always
  ports:
    - 8080:8080
  environment:
    - active.profile=default
  links:
    - users
    - feeds
    - graph
    - octis

