
cache1:
  image: memcached
  expose:
   - 11211
  ports:
   - "11211:11211"

cache2:
  image: memcached
  expose:
   - 11211
  ports:
   - "11212:11211"

redis:
  image: redis
  container_name: redis-cluster
  expose:
    - 6379
  ports:
    - "6379:6379"
  command: redis-server

postgres:
  image: octi/postgres
  container_name: postgres9.5
  expose:
    - 5432
  ports:
      - "5432:5432"
  environment:
    - POSTGRES_DB=octi
    - POSTGRES_USER=octi
    - POSTGRES_PASSWORD=octi

configservice:
  image: octi/configservice:latest
  ports:
    - 8888:8888

discovery:
  image: octi/discovery:latest
  ports:
    - 8761:8761
  links:
    - configservice

users:
  image: octi/users:latest
  container_name: users
  ports:
    - 8585:8585
  links:
    - redis-cluster:redis-cluster
    - discovery
    - configservice
    - cache1
    - cache2
    - postgres9.5:db
  environment:
    - active.profile=default
    - configservice.url=http://configservice:8888
    - discovery.url=http://discovery:8761/eureka/

octis:
  image: octi/octis:latest
  container_name: octis
  ports:
    - 8085:8085
  links:
    - redis-cluster:redis-cluster
    - discovery
    - configservice
    - cache1
    - cache2
    - postgres9.5:db
  environment:
    - active.profile=default
    - configservice.url=http://configservice:8888
    - discovery.url=http://discovery:8761/eureka/

graph:
  image: octi/graph:latest
  container_name: graph
  ports:
    - 9595:9595
  links:
    - redis-cluster:redis-cluster
    - discovery
    - configservice
    - cache1
    - cache2
  environment:
    - active.profile=default
    - configservice.url=http://configservice:8888
    - discovery.url=http://discovery:8761/eureka/

feeds:
    image: octi/feeds:latest
    container_name: feeds
    ports:
      - 9090:9090
    links:
      - redis-cluster
      - discovery
      - configservice
      - cache1
      - cache2
    environment:
      - active.profile=default
      - configservice.url=http://configservice:8888
      - discovery.url=http://discovery:8761/eureka/

